services:
  api:
    build: ./api
    container_name: "triverse_api"
    depends_on:
      - db
    env_file:
      - ./api/.api.env
    ports:
      - "53000:3000"

  db:
    build: ./db
    container_name: "triverse_db"
    env_file:
      - ./db/.db.env
    ports:
      - "53306:3306"
