services:
  api:
    build: ./api
    container_name: "triverse_api"
    depends_on:
      - db
    env_file:
      - ./api/.api.env
    volumes:
      - ./data/music:/app/data/music
      - ./data/chart:/app/data/chart
    ports:
      - "53000:3000"
    user: "1000:1000"

  db:
    build: ./db
    container_name: "triverse_db"
    env_file:
      - ./db/.db.env
    ports:
      - "53306:3306"
