services:
  api:
    build: ./api
    container_name: "tv_api"
    depends_on:
      - db
    env_file:
      - ./api/.api.env
    volumes:
      - ./data/music:/app/data/music
      - ./data/chart:/app/data/chart
    ports:
      - "80:3000"
    user: "1000:1000"

  db:
    build: ./db
    container_name: "tv_db"
    env_file:
      - ./db/.db.env

  session_redis:
    build: ./redis/session
    container_name: "tv_session_redis"
    env_file:
      - ./redis/session/.session.env
